# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "The Bread Runner"
description: >- # this means to ignore newlines until "baseurl:"
  For years I have talked about writing a book. I've talked but nothing comes of items
  I start writing and then life happens. I find a piece of information and write it down...
  Yup where did I put that? Alright I'm writing it all in git.
url: "https://www.pulk.run"
twitter_username: pulkjr
github_username: pulkjr
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Joseph Pulk"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "God Fearing, Husband, Father, American, My views are my own."
  links:
    - label: "pulk.run"
      icon: "fas fa-fw fa-link"
      url: "https://www.pulk.run"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/pulkjr"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pulkjr"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/pulkjr"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pulkjr"

collections:
  recipes:
    output: true
    permalink: /:collection/:path/
  proofs:
    output: true
    permalink: /:collection/:path/
  crums:
    output: true
    permalink: /:collection/:path/
  breads:
    output: true
    permalink: /:collection/:path/

defaults:
  # _recipes
  - scope:
      path: ""
      type: recipes
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _proofs
  - scope:
      path: ""
      type: proofs
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _crums
  - scope:
      path: ""
      type: crums
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _breads
  - scope:
      path: ""
      type: breads
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
